declare namespace Yafc {
  /**
   * An individual input flow for a recipe ingredient in a solved chain.
   * Represents consumption per craft cycle and scaled per second.
   */
  interface RecipeInputFlow {
    /** Direct reference to recipe ingredient specification */
    readonly ingredient: RecipeIngredient;
    /** Quality tier of the consumed ingredient */
    readonly quality: QualityInfo;
    /** Units consumed per single craft cycle */
    readonly amount: number;
    /** Consumption rate in units per second */
    readonly rate: number;
    /** True if this input rate was pinned/constrained by the user */
    readonly isConstraint?: boolean;
  }

  /**
   * An individual output flow for a recipe product in a solved chain.
   */
  interface RecipeOutputFlow {
    /** Direct reference to recipe product specification */
    readonly product: RecipeProduct;
    /** Quality tier of the generated product */
    readonly quality: QualityInfo;
    /** Units generated per single craft cycle */
    readonly amount: number;
    /** Production rate in units per second */
    readonly rate: number;
    /** True if this output rate was pinned/constrained by the user */
    readonly isConstraint?: boolean;
  }

  /**
   * Detailed breakdown and limits for an individual effect type.
   */
  interface RecipeEffectStat {
    /** Effective final bonus value (e.g. 0.5 for +50%, 1.2 for +120%) */
    readonly value: number;
    /** Bonus from machine's own effect_receiver.base_effect */
    readonly base: number;
    /** Bonus specifically from internal modules installed in the machine */
    readonly fromModules: number;
    /** Bonus specifically from external beacon transmissions */
    readonly fromBeacons: number;
    /** Bonus from force research (e.g. infinite productivity research) */
    readonly fromResearch?: number;
    /** Effective maximum limit if configured (< 1000) */
    readonly max?: number;
    /** Effective minimum limit if configured */
    readonly min?: number;
    /** True if the bonus reached or exceeded its configured maximum/minimum limit */
    readonly isCapped?: boolean;
  }

  /**
   * Solved effects breakdown across speed, productivity, energy consumption, and quality.
   */
  interface SolvedRecipeEffects {
    readonly speed: RecipeEffectStat;
    readonly productivity: RecipeEffectStat;
    readonly consumption: RecipeEffectStat;
    readonly quality: RecipeEffectStat;
  }

  /**
   * Solved mathematical result for an individual recipe row in a chain.
   */
  interface SolvedRecipeResult {
    /** Recipe ID */
    readonly recipeId: number;
    /** Direct reference to recipe prototype metadata */
    readonly recipe: RecipeInfo;
    /** Direct reference to machine prototype metadata (contains energySource, etc.) */
    readonly machine: MachineInfo;
    /** Detailed breakdown and limits for all 4 key effects (speed, productivity, consumption, quality) */
    readonly effects: SolvedRecipeEffects;
    /** Exact required machine count */
    readonly machineCount: number;
    /** True if any field in this recipe is pinned/constrained by the user */
    readonly hasConstraint?: boolean;
    /** True if machine count was pinned/constrained by the user */
    readonly isMachineCountConstraint?: boolean;
    /** True if this machine + recipe supports module installation */
    readonly isModuleAllowed: boolean;
    /** True if this machine + recipe supports beacon effects */
    readonly isBeaconAllowed: boolean;
    /** Total power consumption for all machines in Watts (J/s) */
    readonly powerWatts: number;
    /** Selected fuel resource for burner machines */
    readonly fuel?: FuelResource;
    /** Calculated total fuel consumption rate in units/sec */
    readonly fuelRate?: number;
    /** True if fuel rate was pinned/constrained by the user */
    readonly isFuelConstraint?: boolean;
    /** Spent byproduct fuel generated by burner machines (e.g. depleted uranium, spent fluid) */
    readonly spentFuel?: FuelResource;
    /** Calculated total spent fuel generation rate in units/sec */
    readonly spentFuelRate?: number;
    /** List of ingredient consumption flows */
    readonly inputFlows: readonly RecipeInputFlow[];
    /** List of product generation flows */
    readonly outputFlows: readonly RecipeOutputFlow[];
  }

  /**
   * Aggregated flow summary for a specific item, fluid, heat, or electricity across the chain.
   */
  interface ResourceFlowSummary {
    /** Direct reference to resource catalog object (Item, Fluid, Heat, Electricity) */
    readonly resource: ResourceInfo;
    /** Quality tier of this resource flow */
    readonly quality: QualityInfo;
    /** Minimum acceptable fluid temperature for input flows in °C */
    readonly minTemperature?: number;
    /** Maximum acceptable fluid temperature for input flows in °C */
    readonly maxTemperature?: number;
    /** Total units produced per second across all active recipes */
    readonly producedRate: number;
    /** Total units consumed per second across all active recipes */
    readonly consumedRate: number;
    /** Net balance rate in units/s: producedRate - consumedRate */
    readonly netRate: number;
    /** User-configured desired target rate in units/s (if configured) */
    readonly targetRate?: number;
    /** Surplus / extra output rate in units/s: net rate beyond desired target */
    readonly surplusRate: number;
  }

  /**
   * Complete solved mathematical state of a production chain.
   */
  interface SolvedChainSummary {
    /** ID of the solved production chain */
    readonly chainId?: number;
    /** Whether the linear programming solver found a feasible solution */
    readonly isFeasible?: boolean;
    /** Whether cyclic deadlocks or loops exist in the recipe DAG */
    readonly hasDeadlocks?: boolean;
    /** Solved results per recipe keyed by recipeId */
    readonly recipeResults: Record<number, SolvedRecipeResult>;
    /** Target flows matching configured chain targets */
    readonly targetFlows: readonly ResourceFlowSummary[];
    /** External raw materials required by the chain from outside (netRate < 0) */
    readonly inputFlows: readonly ResourceFlowSummary[];
    /** Surplus products produced beyond configured targets (surplusRate > 0) */
    readonly outputFlows: readonly ResourceFlowSummary[];
    /** All aggregated resource flow summaries across the chain */
    readonly summaryFlows: readonly ResourceFlowSummary[];
    /** Total chain power consumption in Watts (J/s) */
    readonly totalPowerWatts: number;
    /** Overall validity flag */
    readonly isValid?: boolean;
    /** Human-readable status or error message */
    readonly statusMessage?: string;
  }
}
