// Auto-generated by fcore style plugin from tailwind.config.cjs. Do not edit manually.
import 'fcore/styles/_tailwind';

declare module 'fcore/styles/_tailwind' {
  interface CustomTailwindTheme {
    'chain-empty-title': true;
    'chain-empty-desc': true;
    'banner-error': true;
    'row-title-cyan': true;
    'row-title-neg': true;
    'row-title-pos': true;
    'table-index': true;
    'power-label': true;
    'stat-label': true;
    'rate-cell': true;
    'rate-input': true;
    'rate-label': true;
    'rate-label-pos': true;
    'rate-label-neg': true;
    'modal-header': true;
    'modal-header-compact': true;
    'modal-actions': true;
    'modal-scroll': true;
    'pin-scroll': true;
    'tab-row': true;
    'tab-btn': true;
    'setting-label': true;
    'setting-slider': true;
    'setting-value': true;
  }
}
